import { AgeRating } from '@prisma/client';

export const movies = [
  {
    title: 'Avengers: Endgame',
    posterUrl: 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
    runtime: 181,
    releaseDate: new Date('2019-04-26'),
    ageRating: AgeRating.T13,
    genreNames: ['Action', 'Adventure', 'Sci-Fi'],
  },
  {
    title: 'The Dark Knight',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    runtime: 152,
    releaseDate: new Date('2008-07-18'),
    ageRating: AgeRating.T16,
    genreNames: ['Action', 'Crime', 'Drama'],
  },
  {
    title: 'Inception',
    posterUrl: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
    runtime: 148,
    releaseDate: new Date('2010-07-16'),
    ageRating: AgeRating.T13,
    genreNames: ['Action', 'Sci-Fi', 'Thriller'],
  },
  {
    title: 'The Shawshank Redemption',
    posterUrl: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=6hB3S9bIaco',
    runtime: 142,
    releaseDate: new Date('1994-09-23'),
    ageRating: AgeRating.T16,
    genreNames: ['Drama', 'Crime'],
  },
  {
    title: 'Parasite',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=5xH0HfJHsaY',
    runtime: 132,
    releaseDate: new Date('2019-05-30'),
    ageRating: AgeRating.T16,
    genreNames: ['Drama', 'Thriller', 'Comedy'],
  },
  {
    title: 'Spider-Man: No Way Home',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=JfVOs4VSpmA',
    runtime: 148,
    releaseDate: new Date('2021-12-17'),
    ageRating: AgeRating.T13,
    genreNames: ['Action', 'Adventure', 'Sci-Fi'],
  },
  {
    title: 'Interstellar',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
    runtime: 169,
    releaseDate: new Date('2014-11-07'),
    ageRating: AgeRating.T13,
    genreNames: ['Sci-Fi', 'Drama', 'Adventure'],
  },
  {
    title: 'The Conjuring',
    posterUrl: 'https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=k10ETZ41q5o',
    runtime: 112,
    releaseDate: new Date('2013-07-19'),
    ageRating: AgeRating.T18,
    genreNames: ['Horror', 'Thriller'],
  },
  {
    title: 'Frozen',
    posterUrl: 'https://image.tmdb.org/t/p/w500/kgwjIb2JDHRhNk13lmSxiClFjc4.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=TbQm5doF_Uc',
    runtime: 102,
    releaseDate: new Date('2013-11-27'),
    ageRating: AgeRating.P,
    genreNames: ['Animation', 'Family', 'Adventure'],
  },
  {
    title: 'Oppenheimer',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
    runtime: 180,
    releaseDate: new Date('2023-07-21'),
    ageRating: AgeRating.T16,
    genreNames: ['Drama', 'War'],
  },
  {
    title: 'The Notebook',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qom1SZSENdmHFNZBXbtJAU0WTlC.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=BjJcYdEOI0k',
    runtime: 123,
    releaseDate: new Date('2004-06-25'),
    ageRating: AgeRating.T13,
    genreNames: ['Romance', 'Drama'],
  },
  {
    title: 'John Wick: Chapter 4',
    posterUrl: 'https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
    runtime: 169,
    releaseDate: new Date('2023-03-24'),
    ageRating: AgeRating.T18,
    genreNames: ['Action', 'Thriller', 'Crime'],
  },
]; 